### PR TITLE
Restructure + Automation

### PR DESCRIPTION
**Pull request by jlmcgehee21**
Why:

* The "flatness" of the project structure was getting messy as I was
adding more files.
* I ordered an initial batch of parts to make four of these sensors and
hope to make many more.  This led me to automate the procedure.

This change addresses the need by:

* Moving files to sensably named directories where applicable.
* Creating jinja2 templates from the original `.ino` file and the
example home assistant config.
* Creating `./bin/generate` which auto-generates an Arduino project and
example home assistant config.

### CODE REVIEW

**Comment by bruhautomation** [comment]
Hello! Thanks for this awesome code. Love the things you've implemented here. I want to play with this code before I merge it because it's such a big change. 

My only concern is that I'd like to maintain an original .ino file that I talk about in the vid. Some people really will just want to copy/paste from the web into a sketch and be off and going. Other people will love this auto generating method. It's sick. 

I'm going to get around to merging this code later this week and probably just maintain an additional .ino for people who want to stick to the original method. 

Thanks much for these additions. They're awesome!

**Comment by jlmcgehee21** [comment]
@bruhautomation, let me know if there is anything I can do to help.. If things work out with this, it's my goal to make a PYPI package so the automation script will be installable via pip.

**Comment by DanielXYZ2000** [comment]
I just hat a look a the changes - really cool!
I would suggest to make a fork for this restructuring and add a link in the README.md file, since this targets more experienced users. Not every windows user has python, hence they migh prefer one single .ino-file

**Comment by jlmcgehee21** [comment]
@DanielXYZ2000 I agree, I haven't had much time to work on this since I approved it, but that seems to be the best path forward.

**Pull request closed without merging**
